
INFO6105 Instructor: Dr. Handan Liu

Homework 1  

Grading: total 100 points.


In [3]:
import numpy as np
arr =np.array([1,2,3])
print(arr)

[1 2 3]


In [5]:
import numpy as np
x=[1,2]
np.asarray(x)
print(x)

[1, 2]


In [6]:
import numpy as np
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [9]:
import numpy as np
a=np.zeros((3,3),int)
np.fill_diagonal(a,1)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
import numpy as np
a=np.full((2,5),6)
print(a)

[[6 6 6 6 6]
 [6 6 6 6 6]]


In [16]:
import numpy as np
a=np.arange(2,101,2)
print(a)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [17]:
import numpy as np
a=np.zeros(10)
y=np.ones(10)*5
print(a)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [2]:
import numpy as np
np.random.seed(0)  
x = np.random.randint(10, size=(3,3,3))  
x

array([[[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2]],

       [[4, 7, 6],
        [8, 8, 1],
        [6, 7, 7]],

       [[8, 1, 5],
        [9, 8, 9],
        [4, 3, 0]]])

In [26]:
import numpy as np
np.random.seed(0)  
x = np.random.randint(10,22, size=(3,4))
print(x)

[[15 10 13 21]
 [13 17 19 13]
 [15 12 14 17]]


In [36]:
import numpy as np
a=np.zeros((5,5))
a[::2, 1::2] = 1
a[1::2, ::2] = 1
print(a)

[[0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]]


In [49]:
import numpy as np
np.random.seed(10) 
np.random.randint(10,size=10)

array([9, 4, 0, 1, 9, 0, 1, 8, 9, 0])

In [61]:
import numpy as np
np.random.seed(0)
np.random.uniform(0,1,size=(3, 2))  

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411]])

In [1]:
import numpy as np
np.random.seed(0)
np.random.uniform(0,4,size=(3, 2))  


array([[2.19525402, 2.86075747],
       [2.4110535 , 2.17953273],
       [1.6946192 , 2.58357645]])

In [3]:
import numpy as np
arr=np.arange(1,10,1)
print(arr)
np.split(arr,[4,6,10])

[1 2 3 4 5 6 7 8 9]


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int32)]

In [54]:
import numpy as np
arr = np.arange(16.0).reshape((4, 4))
left,right=np.hsplit(arr,[2])
print(left)
print(right)

[[ 0.  1.]
 [ 4.  5.]
 [ 8.  9.]
 [12. 13.]]
[[ 2.  3.]
 [ 6.  7.]
 [10. 11.]
 [14. 15.]]


In [6]:
import numpy as np
arr=np.array([[5,10,15],[20,25,30],[35,40,45]] )
row = np.array([[0, 0],[1, 1]])
column = np.array([[1, 2],[1, 2]])
arr[row, column]


array([[10, 15],
       [25, 30]])

In [66]:
import numpy as np
arr=np.array([[5,10,15],[20,25,30],[35,40,45]] )
arr[1,0]

20

In [108]:
import numpy as np
x = np.array([[1, 2, 3],[4,5,6]])
y = np.array([[7, 8, 9],[10,11,12]])
np.concatenate([x, y],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [72]:
import numpy as np
arr=np.array([ 3,  6,  9,  25, 10,  8])
arr[1:]

array([ 6,  9, 25, 10,  8])

In [73]:
import numpy as np
arr=np.array([ 3,  6,  9,  25, 10,  8])
arr[:5]

array([ 3,  6,  9, 25, 10])

In [76]:
arr=np.array([ 3,  6,  9,  25, 10,  8])
arr[0::2]

array([ 3,  9, 10])

In [77]:
arr=np.array([ 3,  6,  9,  25, 10,  8])
arr[1::2]

array([ 6, 25,  8])

In [79]:
import numpy as np
arr=np.array([ 3,  6,  9,  25, 10,  8])
arr[::-1]

array([ 8, 10, 25,  9,  6,  3])

In [2]:
import numpy as np
arr = np.arange(32.0).reshape((8, 4))
print(arr)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]]


In [3]:
import numpy as np
arr = np.arange(32.0).reshape((8, 4))
arr[0,2]=0
print(arr)

[[ 0.  1.  0.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]]


In [7]:
import numpy as np
arr = np.arange(32.0).reshape((8, 4))
arr[:,1]

array([ 1.,  5.,  9., 13., 17., 21., 25., 29.])

In [7]:
import numpy as np
arr = np.arange(32.0).reshape((8, 4))
arr[1:4,  1:4]


array([[ 5.,  6.,  7.],
       [ 9., 10., 11.],
       [13., 14., 15.]])

In [23]:
import numpy as np
x=np.random.random(1000)
mean=np.round(x.mean(),5)
std=np.round(x.std(),5)
var=np.round(x.var(),5)
print("Average of the array elements is: ",mean)
print("Standard deviation of the array elements: ",std)
print("Variance of the array elements: ",var)

Average of the array elements is:  0.48671
Standard deviation of the array elements:  0.27897
Variance of the array elements:  0.07782


In [12]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
print(a.shape)
print(b.shape)
a= a[:, np.newaxis] 
c=a+b
print(c)


(4,)
(3,)
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [107]:
x = np.arange(4)
y = np.ones(5)
x.shape
y.shape
x=x.reshape(4,1)
x+y


array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [27]:
 import numpy as np
a = np.arange(1,7,1)
b=np.arange(1,7,1)
a[:,np.newaxis] * b

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [24]:
for x in range(1, 10):
    print( end=" ")
    for y in range(1, 10):
        print("{:2d}".format(x * y), end=" ")
    print()

  1  2  3  4  5  6  7  8  9 
  2  4  6  8 10 12 14 16 18 
  3  6  9 12 15 18 21 24 27 
  4  8 12 16 20 24 28 32 36 
  5 10 15 20 25 30 35 40 45 
  6 12 18 24 30 36 42 48 54 
  7 14 21 28 35 42 49 56 63 
  8 16 24 32 40 48 56 64 72 
  9 18 27 36 45 54 63 72 81 


In [21]:
import numpy as np
x = np.random.random((10, 3)) #Part 1
print("\n The 10 observations are:\n",x) 
xmean = x.mean(0) #Part 2
print("\nThe mean aggregate across the first dimension:",xmean) 
centered=x-xmean #Part 3
print("\nThe centered array:\n",centered)
y=centered.mean(0) #Part 4
print("\nThe mean aggregate:",y)


 The 10 observations are:
 [[0.4929736  0.69076127 0.06978828]
 [0.2198044  0.14937619 0.60116058]
 [0.19753989 0.05984632 0.30220728]
 [0.67721243 0.57786372 0.33072497]
 [0.83347888 0.27626911 0.26054764]
 [0.55994741 0.47821564 0.44597266]
 [0.15578562 0.50464619 0.25901892]
 [0.39217988 0.73357045 0.93686283]
 [0.77386297 0.40563389 0.59303314]
 [0.74649782 0.41422105 0.36024816]]

The mean aggregate across the first dimension: [0.50492829 0.42904038 0.41595645]

The centered array:
 [[-0.01195469  0.26172089 -0.34616817]
 [-0.28512389 -0.27966419  0.18520414]
 [-0.3073884  -0.36919407 -0.11374916]
 [ 0.17228414  0.14882334 -0.08523148]
 [ 0.32855059 -0.15277128 -0.15540881]
 [ 0.05501912  0.04917526  0.03001622]
 [-0.34914267  0.07560581 -0.15693753]
 [-0.11274841  0.30453006  0.52090638]
 [ 0.26893468 -0.02340649  0.17707669]
 [ 0.24156953 -0.01481933 -0.05570829]]

The mean aggregate: [-1.11022302e-17  1.11022302e-17  2.22044605e-17]
